# Numpy 기초연습문제


In [ ]:
import numpy as np #numpy를 import

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.


In [ ]:
a = np.zeros((3, 4)) # 3행 4열인 ndarray 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.¶

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a #for문을 통해 값 지정

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.


In [ ]:
a[1, 2] #value가 7인 위치

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

array([[5., 6., 7., 8.]])



In [ ]:
a.shape #ad의 형태 확인

(3, 4)

In [ ]:
a[[1], :] # 두번째 행 출력

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.¶

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

In [ ]:
a[:,[0, 2]] #두번째, 세번째 열 출력

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

array([1., 2., 3., 4., 5., 6.])


In [ ]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result
#조건에 따라서 출력하도록 출력

array([1., 2., 3., 4., 5., 6.])

In [ ]:
a[a <= 6]


array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [ ]:
b = np.random.random((3, 4)) #radom-> 랜덤 출력
b

array([[0.29493441, 0.79133895, 0.30471772, 0.25357281],
       [0.66674071, 0.70534894, 0.02569723, 0.03827023],
       [0.53077157, 0.55427973, 0.31973215, 0.81297162]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [ ]:
c = a * b
c

array([[0.29493441, 1.5826779 , 0.91415316, 1.01429122],
       [3.33370353, 4.23209364, 0.17988059, 0.30616182],
       [4.77694412, 5.54279732, 3.51705368, 9.75565942]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.


In [ ]:
d = b.T #전치행렬 x.T
d

array([[0.29493441, 0.66674071, 0.53077157],
       [0.79133895, 0.70534894, 0.55427973],
       [0.30471772, 0.02569723, 0.31973215],
       [0.25357281, 0.03827023, 0.81297162]])

In [ ]:
d.shape#형태확인

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.


In [ ]:
print(a.shape, d.shape)#차원 출력

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.


In [ ]:
e = a.dot(d) #행렬곱 계산 -> x.dot
e

array([[ 3.80605669,  2.30761117,  5.85041396],
       [10.38431222,  8.05183957, 14.72143425],
       [16.96256776, 13.79606796, 23.59245454]])

### 12. e에 대하여 각 열의 합을 계산하시오.


In [ ]:
np.sum(e, axis=1) #각열의 합 계산 np.sum

array([11.96408183, 33.15758604, 54.35109026])